org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

parchment_minecraft_version=1.21.8
parchment_mappings_version=2025.07.18
minecraft_version=1.21.9
neo_version=21.9.2-beta

## Mod Properties
mod_id=cow_tools
mod_name=Cow Tools
mod_version=1.1.2
mod_group_id=telepathicgrunt.cowtools